### ISSUE TITLE
Where can I get twitch Oauth token from?

### ISSUE THREAD

**Issue by fourteen-1** [Garulf/twitchy#15]
How do I retrieve Oauth token or Client ID?

**Comment by Garulf** [comment]
Hello! 

1. First go to the [Twitch developer portal](https://dev.twitch.tv/console/apps). 
2. Create an Application by clicking "Register Your Application".
3. Enter a name and set "OAuth Redirect URLs" to: `http://localhost` (Or your actually redirect URL if you have this set up).
4. Click "Create".
5. Then get the Client ID and Client secret for the new application.


Once you have the `Client ID` & `Client Secret` you may enter these the plugin settings.
A OAuth token will be generated automatically when you activate the plugin.
![image](https://user-images.githubusercontent.com/535299/188559349-fcb374bf-e513-43e3-948d-6d112a9c5fe1.png)

**Comment by fourteen-1** [comment]
Thank you @Garulf. It worked!

**Comment by xathian** [comment]
Nope, doesn't work. Registered app, put the Client ID and Secret into the settings. Typing tw into flowlauncher just says "Missing Credentials" and it empties out the ID/Secret from the settings window
